jobs:
  include:
    - language: python
      python:
        - "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - python3 manage.py makemigrations
        - python3 manage.py migrate
        - cd gradetracker
        - python3 manage.py test